# Sources
OBJS := expat_xmlparser.o libxml_xmlparser.o

OUTFILE = libo.o

CFLAGS += -I ./ -I ../../include/ -I /usr/include/libxml2/ -I /usr/include/ -I ../../src/ -I ../../../libhubbub/include/ -I ../../../libwapcaplet/include/ -I ../../../libwapcaplet/include/
include $(MENUETDEV)/makefiles/Makefile_for_o_lib
