OUTFILE = libo.o

CFLAGS += -I ../../../include/ -I ../../../../ -I ../../ -I /home/sourcerer/kos_src/newenginek/kolibri/include -I ../../../../libwapcaplet/include/ -I ../../../../libparserutils/include/

OBJS = azimuth.o \
background.o \
background_position.o \
border.o \
border_color.o \
border_spacing.o \
border_style.o \
border_width.o \
clip.o \
column_rule.o \
columns.o \
content.o \
css_property_parser_gen.o \
cue.o \
cursor.o \
elevation.o \
font.o \
font_family.o \
font_weight.o \
list_style.o \
list_style_type.o \
margin.o \
opacity.o \
outline.o \
overflow.o \
padding.o \
pause.o \
play_during.o \
properties.o \
quotes.o \
text_decoration.o \
utils.o \
voice_family.o

include $(MENUETDEV)/makefiles/Makefile_for_o_lib
